services:
  time-server:
    image: image.prod.tw/coscup-time-server:latest
    pull_policy: always
    ports:
      - "3000:3000"
    volumes:
      - time-data:/data
    restart: unless-stopped

volumes:
  time-data:
